plugins {
    id 'application'
    id 'war'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Webcam Capture API for QR scanning
    implementation 'com.github.sarxos:webcam-capture:0.3.12'

    // ZXing Library for QR Code Processing
    implementation 'com.google.zxing:core:3.5.0'
    implementation 'com.google.zxing:javase:3.5.0'

    // FlatLaf for Modern UI Design
    implementation 'com.formdev:flatlaf:3.2'

    // MySQL JDBC Driver
    implementation 'mysql:mysql-connector-java:8.0.33'

    // Servlet API
    implementation 'javax.servlet:javax.servlet-api:4.0.1'

    implementation libs.guava
    implementation 'org.jfree:jfreechart:1.5.3'
}

war {
    archiveFileName = 'attendance.war'
}

task runAttendanceApp(type: JavaExec) {
    mainClass = 'project.AttendanceApp'
    classpath = sourceSets.main.runtimeClasspath
}

task runQrScanner(type: JavaExec) {
    mainClass = 'project.QrScanner'
    classpath = sourceSets.main.runtimeClasspath
}

task runQrGenerator(type: JavaExec) {
    mainClass = 'project.QrGenerator'
    classpath = sourceSets.main.runtimeClasspath
}

task runQrDecoder(type: JavaExec) { // Added this task
    mainClass = 'project.QrDecoder'
    classpath = sourceSets.main.runtimeClasspath
}

application {
    mainClass = 'project.App'
}

tasks.named('test') {
    useJUnitPlatform()
}
